// Create an empty HashTable

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

#include <hashtable.h>

int main() {
	HashTable *h = hashtableInit(10);
	hashtablePrint(h);
	return 0;
}
