// Try to lookup something that doesn't exist

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

#include <hashtable.h>
#include <stdio.h>

int main() {
	HashTable *h = hashtableInit(10);
	char *value = hashtableLookup(h, "apple");
	if (value == NULL) {
		printf("NULL");
	} else {
		printf("Not NULL");
	}
	return 0;
}