// Insert into a HashTable

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

#include <hashtable.h>

int main() {
	HashTable *h = hashtableInit(10);
	hashtableInsert(h, "apple", "value1");
	hashtablePrint(h);
	return 0;
}