// Repeatedly insert and remove a <key, value> pair. If your program fails to
// free allocated memory on the remove, this will result in a memory leak and
// the program will terminate.

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

#include <hashtable.h>
#include <stdio.h>
#include <stdlib.h>

int main() {
	HashTable *h = hashtableInit(10);

	int i;
	for (i = 0; i < 1000000; i++) {
        hashtableInsert(h, "", "");
        hashtableRemove(h, "");
	}
	
	printf("Survived");
	
	return 0;
}