// Insert and then remove multiple items

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

#include <hashtable.h>
#include <stdio.h>
#include <stdlib.h>

int main() {
	HashTable *h = hashtableInit(10);

	int i;
	for (i = 0; i < 50; i++) {
		char *newKey = malloc(2 * sizeof(char));
		newKey[0] = 'A' + i;
		newKey[1] = '\0';
		
		// Value is the same as the key
		hashtableInsert(h, newKey, newKey);
	}
	
	
	for (i = 0; i < 50; i++) {
		char *lookupKey = malloc(2 * sizeof(char));
		lookupKey[0] = 'A' + i;
		lookupKey[1] = '\0';
		
		printf("%s\n", hashtableRemove(h, lookupKey));
	}

	hashtablePrint(h);

	return 0;
}