// Insert and then remove

// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE

#include <hashtable.h>
#include <stdio.h>

int main() {
	HashTable *h = hashtableInit(10);
	hashtableInsert(h, "apple", "value1");
	char *value = hashtableRemove(h, "apple");
	printf("%s\n", value);
	hashtablePrint(h);
	return 0;
}