# Makefile for Project 5



all:
	gcc -o problem1 problem1.s
	gcc -o problem2 problem2.s
	gcc -o problem3 problem3.s
	gcc -o problem4 problem4.s
	gcc -o problem5 problem5.s
clean:
	rm problem1
	rm problem2
	rm problem3
	rm problem4
	rm problem5